//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiDefteri_MVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AVP_BILGI_DEFTERIEntities : DbContext
    {
        public AVP_BILGI_DEFTERIEntities()
            : base("name=AVP_BILGI_DEFTERIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BilgiDefteri> BilgiDefteri { get; set; }
        public DbSet<kullanici> kullanici { get; set; }
    }
}
