//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SesinoksPompaProgrami.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRAFIK_EGRI_DEGERLERI
    {
        public int ID { get; set; }
        public Nullable<int> GRAFIK_ID { get; set; }
        public Nullable<decimal> DEGER_1 { get; set; }
        public Nullable<decimal> DEGER_2 { get; set; }
        public Nullable<int> EGRI_TIPI { get; set; }
        public string DEGER_1_BIRIM { get; set; }
        public string DEGER_2_BIRIM { get; set; }
        public Nullable<int> POMPA_ID { get; set; }
        public string TIP { get; set; }
    }
}
