//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SesinoksPompaProgrami.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VerilerEntities : DbContext
    {
        public VerilerEntities()
            : base("name=VerilerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GRAFIKLER> GRAFIKLER { get; set; }
        public virtual DbSet<POMPALAR> POMPALAR { get; set; }
        public virtual DbSet<GRAFIK_EGRI_DEGERLERI> GRAFIK_EGRI_DEGERLERI { get; set; }
    }
}
